### ISSUE TITLE
如果用servlet4.0的pushBuilder ，本地缓存起来，进行重复向设备端推送东西，可以吗？

### ISSUE THREAD

**Issue by zhiyaojieyao** [verhas/pushbuilder#1]
我们项目，需要让设备端可服务端保持长连接，并且，服务端可以随时主动推送给设备端信息。我们的设计，是，设备端开机的时间，访问A接口， A接口缓存了pushBuilder，然后每5分钟ping一下B接口，保持和服务端的长链接。 我们会通过缓存的pushBuilder， 向服务端主动推送信息。但是设备端有时候会收不到。大神们。哪些情况会导致这个问题啊？

**Comment by verhas** [comment]
Although I am not absolutely sure I understood your problem, the situation you describe is crying for a solution of WebSocket rather than server push. These two technologies are somewhat overlapping and it is very common that developers and projects use push instead of WebSocket many times when WebSocket would be a good solution.

Consider using WebSocket on the client side. This will require more client-side programming though. You will also find some samples in my networking tutorial I created for PACKT. This project, you created the issue for is also a spin-off of that tutorial.

Whatever technologies you use you may create some code on the client side that closes all communication channels and opens them fresh when the client sees that there is no communication from the server for a significant amount of time.
